### ISSUE TITLE
gitomator-make-team fails to add students with - in github id

### ISSUE THREAD

**Issue by jmzaleski** [gitomator/gitomator#7]
doesn't seem to like github usernames with - (dash, hyphen) in them.
this likely my misunderstanding of  yaml file syntax:

Students:
  - tony-h-lee
  - kevin-kc
  - moni-li
  - matt-duell
  - Aaron-Tang
  - niki-04
  - anders-leung
  - andrew-x

**Comment by joeyfreund** [comment]
@jmzaleski it is probably YAML related.
Gitomator should handle these names without a problem (in fact, I recognize a few of these usernames from last term).

Can you show me the YAML file you're using?

**Comment by jmzaleski** [comment]
Mathew Zaleski
mobile: 647-223-6005 home: 416-778-8889
94 Hogarth Ave, Toronto, ON, M4K1K4
