### ISSUE TITLE
make-repos could allow property to set upstream remote?

### ISSUE THREAD

**Issue by jmzaleski** [gitomator/gitomator#9]
My current gecko-dev kerfuffle would be less complex to explain to students if gitomator-make-repos knew how to add remotes to the repos it creates. eg:

repo_properties:
  upstream: https://github.com/mozilla/gecko-dev

or even:

repo_properties:
   remote: {upstream: https://github.com/mozilla/gecko-dev}

**Comment by joeyfreund** [comment]
This will require some thinking ... Gitomator can do stuff to your hosted GitHub repos, but, unless I am misunderstanding, what you are talking about is defining remotes in the students' *local* clones.

**Comment by jmzaleski** [comment]
doh i was thinking that if you put the remote into the local clone in /tmp
then it would survive the push. no way.
